"""OroTitan Nexus equity screener package."""

from . import (
    api,
    backtest,
    cli,
    cli_cac40_garp,
    cli_custom_garp,
    cli_garp_backtest,
    cli_garp_diagnostics,
    config,
    diagnostics,
    data_fetch,
    factors_v2,
    filters,
    garp_rules,
    history,
    normalization,
    orchestrator,
    prices,
    reporting,
    scoring,
    scoring_v2,
    universe,
)

__all__ = [
    "api",
    "backtest",
    "cli",
    "cli_cac40_garp",
    "cli_custom_garp",
    "cli_garp_backtest",
    "cli_garp_diagnostics",
    "config",
    "diagnostics",
    "data_fetch",
    "factors_v2",
    "filters",
    "garp_rules",
    "history",
    "normalization",
    "orchestrator",
    "prices",
    "reporting",
    "scoring",
    "scoring_v2",
    "universe",
]
__version__ = "0.1.0"
